language: objective-c

#osx_image: xcode7.2
#xcode_workspace: Example/NGSPopoverView.xcworkspace
#xcode_scheme: NGSPopoverViewExample
#xcode_sdk: iphonesimulator9.2

before_install:
- pod lib lint
- gem install xcpretty
- pod install --project-directory=Example

xcode_workspace: Example/NGSPopoverView.xcworkspace
xcode_scheme: NGSPopoverViewExample